version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: mydb 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
  web:
    build: ./imgs
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html/
